version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/user_service
hooks:
  AfterInstall:
    - location: deploy_scripts/cleanup_script.sh
      timeout: 300
      runas: ec2-user